spring:
  cloud:
    aws:
      s3:
        bucket: ${AWS_BUCKET}
      region:
        static: ${AWS_REGION}
      credentials:
          access-key: ${AWS_ACCESS_KEY}
          secret-key: ${AWS_SECRET_KEY}
  application:
    name: review-x

  output:
    ansi:
      enabled: always

  security:
    user:
      name: "admin"
      password: "root"

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
      repositories:
        enabled: false
    redis:
      url: ${SPRING_DATA_REDIS_URL}
      client-type: lettuce
      connect-timeout: 3s
      timeout: 5s


  main:
    lazy-initialization: true

app:
  mongodb:
    games:
      uri: ${MONGODB_URI_GAMES}
  frontend:
    url: ${FRONTEND_URL}
  security:
    refresh-path: /api/auth/refresh
    allowed-origins: "http://localhost:3000,https://loggvault.com"

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: logs/app.log
  level:
    root: warn
    io:
      lettuce:
        core: DEBUG
    com:
      idealizer:
        review_x: trace
    org:
      springframework:
        web: info
        security: info
        data:
          redis: DEBUG

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  override-with-generic-response: true
server:
  port: 9090
  error:
    whitelabel:
      enabled: false
