spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1038586768437-krad9cntheo8q90cls349nur767ac9m6.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/review_x
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
  main:
    lazy-initialization: true
app:
  config:
    variavel: x